version: '3.3'

services:
  sauvcmaster:
    build: .
    image: leonardo/sauvcmaster
    container_name: sauvcmaster
    network_mode: "host"
    stop_signal: SIGINT
  hardware_interface:
    build:
      dockerfile: Dockerfile.hardware
      context: .
    container_name: hardware_interface
    network_mode: "host"
    privileged: true
    environment:
      - DISPLAY=unix$DISPLAY
      - MACHINE=${MACHINE}
    shm_size: 256M
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /dev:/dev
      - ./catkin_ws/src/sauvc:/home/leonardo/catkin_ws/src/sauvc
      - ./catkin_ws/src/rosserial:/home/leonardo/catkin_ws/src/rosserial
      - ~/Arduino/libraries:/home/leonardo/Arduino/libraries
      - ./build_arduino_lib.sh:/home/leonardo/Arduino/libraries/build_arduino_lib.sh
    stop_signal: SIGINT
    working_dir: /home/leonardo
    command: bash -c "./Arduino/libraries/build_arduino_lib.sh && sleep infinity"
